name 'puppetlabs-dhcp'
version '1.1.1'
source 'git://github.com/puppetlabs/puppetlabs-dhcp.git'
author 'puppetlabs'
license 'Apache License Version 2.0'
summary 'Manage the ISC DHCP Daemon'
description 'A Puppet module to deploy and manage the ISC DHCP server.'
project_page 'https://github.com/puppetlabs/puppet-dhcp'

dependency 'ripienaar/concat', '>= 0.1.0'
